### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '-oX': '-oX'

### ISSUE THREAD

**Issue by sirb0rab0g1** [wangoloj/python3-nmap#10]
i was using pipenv to make venv but this error goes out after excuting a funciton

**Comment by wangoloj** [comment]
Do you have nmap installed?
Try to install nmap and test again

**Comment by sw33tr0ll** [comment]
I am having this issue as well, with Google App Engine. @wangoloj are you saying to install the actual nmap binary to resolve this?

**Comment by sw33tr0ll** [comment]
Following up, it looks like the App Engine issue is due to the "standard" environment being pretty limited in it's abilities to write files. Might help to change the default output file from "-" to something else too.

**Comment by wangoloj** [comment]
Yes, you have to install nmap;
`sudo apt-get install nmap`
If the issue persisters after installing nmap then let us now

**Comment by barbaart** [comment]
> Yes, you have to install nmap;
> `sudo apt-get install nmap`
> If the issue persisters after installing nmap then let us now

Can confirm this. Had the same issue using the package in my django project on a docker container. After a `apt-get install nmap` it all worked fine!
