### ISSUE TITLE
Stealh scan vs firewall detection

### ISSUE THREAD

**Issue by haydar-tech** [wangoloj/python3-nmap#13]
Hi,

In this part of the code you use both same option for two different functions. For Stealth Scan I suggest you use : `-T[0:1:2]` or `-sZ` for sctp (Stream Control Transmission Protocol) cookie echo, otherwise combine any option with `-n` and `-Pn`.

 ```
def nmap_stealth_scan(self, host, arg="-sA", args=None):
        """
        nmap -oX - nmmapper.com -sA
        """
...

def nmap_detect_firewall(self, host, arg="-sA", args=None): # requires root
        """
        nmap -oX - nmmapper.com -sA
        @ TODO
        """
```

**Comment by wangoloj** [comment]
Thanks for those ideas, am going to start working on them.

**Comment by haydar-tech** [comment]
Thank you for having changed the options.
I will close these issue.
