### ISSUE TITLE
wrong handling of xml.etreeElementTree objects

### ISSUE THREAD

**Issue by lesinigo** [wangoloj/python3-nmap#19]
This library has code like this in multiple places:
```python
if (some_xml_element.find('something_else')):
    do_some_stuff
```

Under some Python / xml.etree versions this will not work as intended, for example I am getting this output from `Nmap().nmap_version_detection()` (notice missing information about port state and service exposed on the port):
```
{'port': '443',
 'protocol': 'tcp'}
```

In the case of `Nmap().nmap_version_detection()` this happens because `<state>` and `<service>` do not have any further sub-elements and [as the docs say](https://docs.python.org/3.8/library/xml.etree.elementtree.html#element-objects):

> Elements with no subelements will test as False. This behavior will change in future versions. Use specific len(elem) or elem is None test instead.

Changing `if(port.find("service")):` with `if port.find("service") is not None:` will restore correct behaviour and give complete results like:
```
 {'port': '443',
  'protocol': 'tcp',
  'reason': 'syn-ack',
  'reason_ttl': '0',
  'service': {'conf': '10',
              'devicetype': 'security-misc',
              'method': 'probed',
              'name': 'http',
              'product': 'Fortinet security device httpd',
              'tunnel': 'ssl'},
  'state': 'open'}]
```

**Comment by wangoloj** [comment]
Thank you for that insight. Will get time to fix that, Also if you can open a pull request about it that would be fine.

**Comment by lesinigo** [comment]
I sent pr #21 with some untested code, I will use that in my development but I will be able to test only some of the code paths.

**Comment by wangoloj** [comment]
okay

**Comment by lesinigo** [comment]
thank you for merging. as far as I can tell this issue should be resolved, but I hadn't exercised all possible code paths.
If you feel confident about the changes I'd propose to close this issue as resolved.

**Comment by lesinigo** [comment]
oh and if you could cut a new release on PyPI that would be great

**Comment by wangoloj** [comment]
Okay let get that done.

**Comment by lesinigo** [comment]
Thank you @wangoloj for your quick support, you've been very helpful.

As far as I can tell this problem is now fixed in code and also in the PyPI released version, I'm closing the issue.
