### ISSUE TITLE
Forgot filter_subdomains?

### ISSUE THREAD

**Issue by ioncodes** [wangoloj/python3-nmap#2]
I'm trying to get the snippet below to run. Looks like `filter_subdomains` is indeed not declared anywhere!

```
Python 3.7.6 (default, Dec 30 2019, 19:38:26)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nmap3
>>> nmap = nmap3.Nmap()
>>> nmap.nmap_dns_brute_script("google.ch")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/3.7/lib/python/site-packages/nmap3/nmap3.py", line 115, in nmap_dns_brute_script
    subdomains = self.filter_subdomains(xml_root)
AttributeError: 'Nmap' object has no attribute 'filter_subdomains'
```

**Comment by wangoloj** [comment]
Okay let me test it out and checkout the lastest I have

**Comment by wangoloj** [comment]
Thank you for reporting I have fixed this bug and Updated the pypi.org so you can updated your local packages and test again, before the issue is closed.

**Comment by wangoloj** [comment]
Results are assigned back not printed in realtime
you will need something like this

`results = nmap.nmap_dns_brute_script("google.ch")`

**Comment by ioncodes** [comment]
Thanks for the quick fix, it works now! I was testing it in the Python REPL so an assignment is not needed to print it to the console ;)
