### ISSUE TITLE
I have a really important question 

### ISSUE THREAD

**Issue by ReaperZ0v** [wangoloj/python3-nmap#24]
Can this library be used in a python application which will be used and/or sold  commercially?

**Comment by wangoloj** [comment]
That's a YES, it's entirely up to you to choose how to use it commercial or opensource.

**Comment by ReaperZ0v** [comment]
Thank you

**Comment by lesinigo** [comment]
@ReaperZ0v this library is currently under the GPL v3 so you must obey to that license. Up to you to understand what you can or cannot do, but you should be able to use the library in an application that will be sold commercially as long as you do not modify the library itself.

For more details refer to the included [LICENSE](https://github.com/wangoloj/python3-nmap/blob/master/LICENSE) file.

**Comment by ReaperZ0v** [comment]
> @ReaperZ0v this library is currently under the GPL v3 so you must obey to that license. Up to you to understand what you can or cannot do, but you should be able to use the library in an application that will be sold commercially as long as you do not modify the library itself.
> 
> 
> 
> For more details refer to the included [LICENSE](https://github.com/wangoloj/python3-nmap/blob/master/LICENSE) file.

Thanks fo reaching out! Nah I got nothing to do with modifying even a code bit of the library I just wanna use its functionalities, classes and methods in my commercial app so is it allowed?
