### ISSUE TITLE
Add support for individual arguments being sudo instead of needing the whole script be sudo

### ISSUE THREAD

**Issue by santiago-espinosa** [wangoloj/python3-nmap#27]
Is there a way of having only one scan be run as root?
I want to avoid running my whole script as root as it also doing other things (such as storing data in json files) that I want to do a s a standard user.

I've looked at the code and the documentation but I haven't found any ways of having the module prompt the user for superuser access for a specific command.

**Comment by wangoloj** [comment]
This is an interesting issue, i see your concern, unfortunately right now, there is no way of doing that in the script, but you can do something custom in your script as you wait for the solution on our part, I will surely find a way of doing it and update this issue.

**Comment by santiago-espinosa** [comment]
Here's a few solutions for elevating privileges with [windows](https://stackoverflow.com/questions/19672352/how-to-run-python-script-with-elevated-privilege-on-windows) and [linux](https://stackoverflow.com/questions/13045593/using-sudo-with-python-script) if it helps.
I'll try cloning and branching to see whether I can get it working consistently on both linux and windows on Monday

**Comment by santiago-espinosa** [comment]
Ok, so I found an easy solution:

1) Add a secondary default_comman(self) function called default_command_privileged(self) which will return 

```
   def default_command_privileged(self):
        os_type = sys.platform
        if os_type == 'win32':
            # Elevate privileges and return nmap command
        else:
        cmd = "which nmap"
        return self.default_args.format(nmap="sudo "+self.nmaptool, outarg="-oX")
        #the sudo part of the command will ask for a password by itself
```
For windows UAC, you can implement this code to elevate privileges:
https://gist.github.com/sylvainpelissier/ff072a6759082590a4fe8f7e070a4952

**Comment by wangoloj** [comment]
Okay great solution.

**Comment by Luciogi** [comment]
Hi, sudo is not passed to `scan_command()`

can this be fixed ?
