### ISSUE TITLE
the function "nmap3.Nmap().nmap_version_detection()" seems that it has a problem

### ISSUE THREAD

**Issue by bobolike123** [wangoloj/python3-nmap#29]
in nmap3\nmapparser.py  the function "version_detection()" has not defined the variable "service_version_dict". when I used the "nmap3.Nmap().nmap_version_detection()" to call the "version_detection()", it raised "NameError: name 'service_version_dict' is not defined".

ps: I programmed my code at Win10 OS

**Comment by wangoloj** [comment]
Okay thanks for reporting we shall investigate and fix it immediately.

**Comment by wangoloj** [comment]
It seems you are calling the wrong way

```
import nmap3
nmap = nmap3.Nmap()
version = nmap.nmap_version() # works
version_result = nmap.nmap_version_detection("your-host.com")
```

That is how you all nmap_version_detection to detect versions on hosts.

**Comment by bobolike123** [comment]
the function 【nmap.nmap_version()】can work properly, but【nmap.nmap_version_detection("my-host.com")】still get wrong. I have tried to change the args from "my-host.com" to "www.my-host.com" even the ipv4 address. They got the same wrong 【'service_version_dict' is not defined"】
Strangely,if I use the 【nmap.scan_top_ports("www.my-host.com",args='-sV')】 instead, it can return the result without any wrong.

By the way, I define the path of 【namp.exe】 and the code is 【nmap = nmap3.Nmap(path=‘my-nmap_exe-path’)】rather than 【nmap=namp3.Nmap()】because my operating system can not find the namp.exe automatically

Is it the problem of my OS?Because I understand that some code programmed at Linux will yield wrong at Win.

The detailed traceback of the information is listed below:
Traceback (most recent call last):
  File "F:/pyCode/generator.py", line 127, in <module>
    run('version_detection')
  File "F:/pyCode/generator.py", line 106, in run
    js = _namp3_version_detection(url)
  File "F:/pyCode/generator.py", line 60, in _namp3_version_detection
    json_result = nmap.nmap_version_detection(host)
  File "F:\Anaconda3\lib\site-packages\nmap3\nmap3.py", line 178, in nmap_version_detection
    services = self.parser.version_parser(xml_root)
  File "F:\Anaconda3\lib\site-packages\nmap3\nmapparser.py", line 393, in version_parser
    raise(e)
  File "F:\Anaconda3\lib\site-packages\nmap3\nmapparser.py", line 390, in version_parser
    service_version_dict[address] = services_result
NameError: name 'service_version_dict' is not defined

Process finished with exit code 1

**Comment by wangoloj** [comment]
Alright, let me look into it again.

**Comment by wangoloj** [comment]
This was a bug, but now it has been fixed. You can update the local installation from git we have not pushed the changes to pypi

pip3 install git+https://github.com/wangoloj/python3-nmap.git

**Comment by bobolike123** [comment]
thanks for your effort ！ :)
