### ISSUE TITLE
nmap_dns_brute_script doesn't work properly

### ISSUE THREAD

**Issue by ioncodes** [wangoloj/python3-nmap#3]
When I run `nmap.nmap_dns_brute_script("google.com")` a few times it will eventually get the hostname and address wrong.
Expected:
```
[{'address': '172.217.168.46', 'hostname': 'admin.google.com'},...
```
What I get sometimes:
```
[{'address': 'admin.google.com', 'hostname': '172.217.168.46'},...
```

**Comment by wangoloj** [comment]
Alright, let me look into it, Thank you.

**Comment by ioncodes** [comment]
Any progress on this issue?

**Comment by wangoloj** [comment]
I have been investigating this, I suspect it's an nmap problem the way it returns the data or my own sorting problem

i```
f(len(elem) >= 2):
                        address = elem[0]
                        hostname = elem[1]
                        
                        script_results["address"]=address.text 
                        script_results["hostname"]=hostname.text 
                        subdomains_list.append(script_results)
```

**Comment by ioncodes** [comment]
The pull request should fix the issue

**Comment by wangoloj** [comment]
@ioncodes  Thank you soo much, let me get the merge done.
