### ISSUE TITLE
parsing xml results

### ISSUE THREAD

**Issue by deontpearson** [wangoloj/python3-nmap#6]
Hi, question regarding parsing the response. I noticed the response for a call such as `nmap.nmap_ping_scan("10.0.0.0/24")` will not return a list of responses , it only returns the first host found. 

The response gets passed to [https://github.com/wangoloj/python3-nmap/blob/32c35be8b7db3fa5a464a723439c02bd95662897/nmap3/nmapparser.py#L112](url) and the code does `xml_root.find("host")` which returns the first host in the response. Is this the intended behaviour? 

I would imagine this should rather iterate through  `xml_root.findall("host")` and return a list responses.

**Comment by wangoloj** [comment]
@deontpearson  Thanks for point that out, I will fix it on the next changes am working on. Also if you can open a pull request that's okay.

**Comment by deontpearson** [comment]
I have a partial fix for that I modified for a small test I was running. I will make it PR worthy and open one.

Are you working on the NmapHostDiscovery by chance? Those functions have been useful to me too.

**Comment by wangoloj** [comment]
Yes, those are the changes am working on NmapHostDiscovery, am about to finish them.
