### ISSUE TITLE
Locate nmap on windows

### ISSUE THREAD

**Issue by 0ogway** [wangoloj/python3-nmap#8]
Hey guys, 

When using python3-nmap in a Windows 10 environment (nmap is within env variables), getting an error when the get_nmap_path() method is ran. From a quick look its because its only trying "which nmap" which is a unix command. 

Is Windows compatibility planned?

Thanks.

**Comment by wangoloj** [comment]
@0ogway We currently working to fix that error, that's for reporting. Feel free to open a Pull request if you fix it before we do.
